enum EMPLOYEE_CONSTANTS {
  CREATE_EMPLOYEE = "CREATE_EMPLOYEE",
  UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE",
  DELETE_EMPLOYEE = "DELETE_EMPLOYEE",
  DELETE_ALL_EMPLOYEE = "DELETE_ALL_EMPLOYEE",
  LOAD_EMPLOYEE = "LOAD_EMPLOYEE",
}

export { EMPLOYEE_CONSTANTS };
